apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: isolation
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - gitops-demo-frontend-prod
              - istio-gateway
