github_sha = os.environ.get("GITHUB_SHA", "local")[:7]

docker_build(
  'localhost:5001/gitops-playground/frontend',
  '.',
  only = [
    'Dockerfile',
    'go.mod',
    'main.go',
    'static',
    'template'
  ],
  extra_tag = [
    'localhost:5001/gitops-playground/frontend:ci-%s' % github_sha
  ]
)
