github_sha = os.environ.get("GITHUB_SHA", "local")[:7]

docker_build(
  'localhost:5001/gitops-demo/backend',
  '.',
  only = [
    'Dockerfile',
    'go.mod',
    'main.go',
  ],
    extra_tag = [
      'localhost:5001/gitops-demo/backend:ci-%s' % github_sha
    ]
)
