apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    version: v1.1.0
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: /frontend
      labels:
        app: frontend
        version: v1.1.0
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: backend-config-tk67b995gg
            optional: false
        image: ghcr.io/procinger/gitops-demo-frontend/frontend:v1.5.1
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
        name: frontend
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
      imagePullSecrets:
      - name: ghcr-io
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: frontend
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtualservice
spec:
  gateways:
  - istio-gateway/kubedev-net
  hosts:
  - dev.pg.lab.kubedev.net
  http:
  - directResponse:
      body:
        string: Forbidden
      status: 403
    match:
    - uri:
        prefix: /healthz
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    version: v1.1.0
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: /backend
      labels:
        app: backend
        version: v1.1.0
    spec:
      containers:
      - image: ghcr.io/procinger/gitops-demo-frontend/backend:v1.5.1
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
            scheme: HTTP
        name: backend
        ports:
        - containerPort: 8080
          name: api
        readinessProbe:
          httpGet:
            path: /api/time
            port: api
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
      imagePullSecrets:
      - name: ghcr-io
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - appProtocol: http
    name: http-api
    port: 80
    targetPort: api
  selector:
    app: backend
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: isolation
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - gitops-demo-frontend-dev
        - istio-gateway
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: strict-mtls
spec:
  mtls:
    mode: STRICT
---
apiVersion: v1
data:
  BACKEND_URL: http://backend
kind: ConfigMap
metadata:
  name: backend-config-tk67b995gg
