# Install Istio
include('./istio/Tiltfile')

# start local LoadBalancer
include('./loadbalancer/Tiltfile')

# Install Jaeger
include('./jaeger/Tiltfile')

# Install Kiali
include('./kiali/Tiltfile')

# Install Prometheus
include('./prometheus/Tiltfile')

# Install OpenTelemetry Collector
include('./otel-collector/Tiltfile')
