apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: local-dev

patches:
  - path: patches/virtualservice.yaml
    target:
      kind: VirtualService
      name: virtualservice

  - path: patches/isolation.yaml
    target:
      kind: AuthorizationPolicy
      name: isolation

  - path: patches/deployment.yaml
    target:
      kind: Deployment

configMapGenerator:
  - name: backend-config
    literals:
      - BACKEND_URL=http://backend

images:
  - name: ghcr.io/procinger/gitops-demo-frontend/frontend
    newName: localhost:5001/gitops-demo/frontend

  - name: ghcr.io/procinger/gitops-demo-frontend/backend
    newName: localhost:5001/gitops-demo/backend
