load('ext://helm_resource', 'helm_repo', 'helm_resource')

helm_repo(
  'jaegertracing',
  'https://jaegertracing.github.io/helm-charts'
)

helm_resource(
  'jaeger',
  'jaegertracing/jaeger',
  resource_deps = ['istio'],
  namespace = 'observability',
  labels = 'System',
  flags = [
    '--version=4.3.4',
    '--create-namespace',
    '--set=query.enabled=false',
    '--set=provisionDataStore.cassandra=false',
    '--set=allInOne.enabled=true',
    '--set=storage.type=memory',
    '--set=agent.enabled=false',
    '--set=collector.enabled=false',
  ],
  auto_init = False,
)

k8s_resource(
  workload = 'jaeger',
  labels = ['System'],
  port_forwards = '16686:16686',
)
