apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtualservice
spec:
  gateways:
    - istio-gateway/kubedev-net
  hosts:
    - prod.pg.lab.kubedev.net
  http:
    # disable /healthz endpoint
    - match:
        - uri:
            prefix: /healthz
      directResponse:
        status: 403
        body:
          string: "Forbidden"
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend
            port:
              number: 80
